-- Mario constants
OMM_MARIO_WALL_SLIDE_JUMP_ANGLE_MAX     = 0x1000
OMM_MARIO_HANG_MAX_SPEED                = 16.0
OMM_MARIO_ROLL_MIN_SPEED                = 30.0
OMM_MARIO_ROLL_MAX_SPEED                = 120.0
OMM_MARIO_ROLL_DECEL                    = 1.5
OMM_MARIO_ROLL_YAW_VEL                  = 0x180
OMM_MARIO_SPIN_DURATION                 = 30
OMM_MARIO_SPIN_BUFFER_DURATION          = 6
OMM_MARIO_SPIN_MIN_HIT_CHECKPOINTS      = 5

-- Actions
ACT_FLAG_OMM_ACTION                     = (1 << 30)

-- Stationary
ACT_OMM_SPIN_GROUND                     = (0x00 | ACT_GROUP_STATIONARY | ACT_FLAG_OMM_ACTION | ACT_FLAG_STATIONARY)

-- Moving
ACT_OMM_ROLL                            = (0x00 | ACT_GROUP_MOVING | ACT_FLAG_OMM_ACTION | ACT_FLAG_MOVING | ACT_FLAG_SHORT_HITBOX)

-- Airborne
ACT_OMM_GROUND_POUND_JUMP               = (0x00 | ACT_GROUP_AIRBORNE | ACT_FLAG_OMM_ACTION | ACT_FLAG_AIR | ACT_FLAG_ALLOW_VERTICAL_WIND_ACTION)
ACT_OMM_WALL_SLIDE                      = (0x01 | ACT_GROUP_AIRBORNE | ACT_FLAG_OMM_ACTION | ACT_FLAG_AIR)
ACT_OMM_ROLL_AIR                        = (0x02 | ACT_GROUP_AIRBORNE | ACT_FLAG_OMM_ACTION | ACT_FLAG_AIR | ACT_FLAG_ALLOW_VERTICAL_WIND_ACTION | ACT_FLAG_SHORT_HITBOX)
ACT_OMM_SPIN_AIR                        = (0x03 | ACT_GROUP_AIRBORNE | ACT_FLAG_OMM_ACTION | ACT_FLAG_AIR | ACT_FLAG_ALLOW_VERTICAL_WIND_ACTION)
ACT_OMM_SPIN_JUMP                       = (0x04 | ACT_GROUP_AIRBORNE | ACT_FLAG_OMM_ACTION | ACT_FLAG_AIR | ACT_FLAG_ALLOW_VERTICAL_WIND_ACTION)
ACT_OMM_MIDAIR_SPIN                     = (0x05 | ACT_GROUP_AIRBORNE | ACT_FLAG_OMM_ACTION | ACT_FLAG_AIR | ACT_FLAG_ALLOW_VERTICAL_WIND_ACTION)
ACT_OMM_CAPPY_BOUNCE                    = (0x11 | ACT_GROUP_AIRBORNE | ACT_FLAG_OMM_ACTION | ACT_FLAG_AIR | ACT_FLAG_ALLOW_VERTICAL_WIND_ACTION)
ACT_OMM_CAPPY_VAULT                     = (0x12 | ACT_GROUP_AIRBORNE | ACT_FLAG_OMM_ACTION | ACT_FLAG_AIR | ACT_FLAG_ALLOW_VERTICAL_WIND_ACTION)

-- Submerged
ACT_OMM_WATER_GROUND_POUND              = (0x00 | ACT_GROUP_SUBMERGED | ACT_FLAG_OMM_ACTION | ACT_FLAG_SWIMMING)
ACT_OMM_WATER_GROUND_POUND_LAND         = (0x01 | ACT_GROUP_SUBMERGED | ACT_FLAG_OMM_ACTION | ACT_FLAG_METAL_WATER) -- not ACT_FLAG_SWIMMING, so Mario can interact with underwater objects
ACT_OMM_WATER_GROUND_POUND_JUMP         = (0x02 | ACT_GROUP_SUBMERGED | ACT_FLAG_OMM_ACTION | ACT_FLAG_SWIMMING)
ACT_OMM_WATER_DASH                      = (0x03 | ACT_GROUP_SUBMERGED | ACT_FLAG_OMM_ACTION | ACT_FLAG_SWIMMING)

-- Sounds
OMM_SOUND_ACTION_SPIN                   = 0x04378081
OMM_SOUND_ACTION_TWIRL                  = 0x04388081
OMM_SOUND_ACTION_SIDE_FLIP              = 0x045A8081
OMM_SOUND_ACTION_WATER_GP               = 0x0430C081
OMM_SOUND_ACTION_WATER_DASH             = 0x04348081
OMM_SOUND_TERRAIN_SLIDE                 = 0x14000001
OMM_SOUND_TERRAIN_HEAVY_LANDING         = 0x04608081
