-- Cappy constants
OMM_CAPPY_LIFETIME                      = 120
OMM_CAPPY_RETURN_VEL                    = 120
OMM_CAPPY_SLOWDOWN_FACTOR               = 1.15
OMM_CAPPY_HITBOX_RADIUS                 = 88
OMM_CAPPY_HITBOX_HEIGHT                 = 128
OMM_CAPPY_HITBOX_OFFSET                 = 48
OMM_CAPPY_WALL_RADIUS                   = 56
OMM_CAPPY_GFX_SCALE_X                   = 1.2
OMM_CAPPY_GFX_SCALE_Y                   = 1.1
OMM_CAPPY_GFX_SCALE_Z                   = 1.2
OMM_CAPPY_GFX_ANGLE_VEL                 = 0x2000
OMM_CAPPY_GFX_VANISH_ALPHA              = 0x80
OMM_CAPPY_HOMING_VELOCITY               = 80
OMM_CAPPY_HOMING_DURATION               = 5

-- Default throw
OMM_CAPPY_BHV_DEFAULT_GROUND            = 0
OMM_CAPPY_BHV_DEFAULT_AIR               = 1
OMM_CAPPY_BHV_DEFAULT_OFFSET            = 50
OMM_CAPPY_BHV_DEFAULT_VEL               = 144
OMM_CAPPY_BHV_DEFAULT_CALL_BACK_START   = 10

-- Upwards throw
OMM_CAPPY_BHV_UPWARDS_GROUND            = 2
OMM_CAPPY_BHV_UPWARDS_AIR               = 3
OMM_CAPPY_BHV_UPWARDS_OFFSET            = 40
OMM_CAPPY_BHV_UPWARDS_VEL               = 80
OMM_CAPPY_BHV_UPWARDS_CALL_BACK_START   = 10

-- Downwards throw
OMM_CAPPY_BHV_DOWNWARDS_GROUND          = 4
OMM_CAPPY_BHV_DOWNWARDS_AIR             = 5
OMM_CAPPY_BHV_DOWNWARDS_OFFSET          = 40
OMM_CAPPY_BHV_DOWNWARDS_VEL             = 100
OMM_CAPPY_BHV_DOWNWARDS_CALL_BACK_START = 10

-- Spin throw
OMM_CAPPY_BHV_SPIN_GROUND               = 6
OMM_CAPPY_BHV_SPIN_AIR                  = 7
OMM_CAPPY_BHV_SPIN_OFFSET               = 60
OMM_CAPPY_BHV_SPIN_RADIUS_MAX           = 240
OMM_CAPPY_BHV_SPIN_RADIUS_GROWTH        = 16
OMM_CAPPY_BHV_SPIN_ANGLE_VEL            = 0x1000
OMM_CAPPY_BHV_SPIN_CALL_BACK_START      = 16

-- Flying throw
OMM_CAPPY_BHV_FLYING                    = 8
OMM_CAPPY_BHV_FLYING_OFFSET             = 30
OMM_CAPPY_BHV_FLYING_RADIUS_MAX         = 180
OMM_CAPPY_BHV_FLYING_RADIUS_GROWTH      = 12
OMM_CAPPY_BHV_FLYING_ANGLE_VEL          = 0x1000
OMM_CAPPY_BHV_FLYING_CALL_BACK_START    = 16

-- Cappy collision handlers
OMM_CAPPY_COL_WALL_DEFAULT              = 1
OMM_CAPPY_COL_WALL_FULL_STOP            = 2
OMM_CAPPY_COL_FLOOR_CHANGE_BEHAVIOR     = 1

-- Actions
ACT_FLAG_OMM_ACTION                     = (1 << 30)

-- Stationary
ACT_OMM_SPIN_GROUND                     = (0x00 | ACT_GROUP_STATIONARY | ACT_FLAG_OMM_ACTION | ACT_FLAG_STATIONARY)

-- Moving
ACT_OMM_CAPPY_THROW_GROUND              = (0x10 | ACT_GROUP_MOVING | ACT_FLAG_OMM_ACTION | ACT_FLAG_MOVING)

-- Airborne
ACT_OMM_SPIN_AIR                        = (0x03 | ACT_GROUP_AIRBORNE | ACT_FLAG_OMM_ACTION | ACT_FLAG_AIR | ACT_FLAG_ALLOW_VERTICAL_WIND_ACTION)
ACT_OMM_CAPPY_THROW_AIRBORNE            = (0x10 | ACT_GROUP_AIRBORNE | ACT_FLAG_OMM_ACTION | ACT_FLAG_AIR)
ACT_OMM_CAPPY_BOUNCE                    = (0x11 | ACT_GROUP_AIRBORNE | ACT_FLAG_OMM_ACTION | ACT_FLAG_AIR | ACT_FLAG_ALLOW_VERTICAL_WIND_ACTION)
ACT_OMM_CAPPY_VAULT                     = (0x12 | ACT_GROUP_AIRBORNE | ACT_FLAG_OMM_ACTION | ACT_FLAG_AIR | ACT_FLAG_ALLOW_VERTICAL_WIND_ACTION)

-- Submerged
ACT_OMM_CAPPY_THROW_WATER               = (0x10 | ACT_GROUP_SUBMERGED | ACT_FLAG_OMM_ACTION | ACT_FLAG_SWIMMING)

-- Sounds
OMM_SOUND_ACTION_BOING                  = 0x306C4081
OMM_SOUND_OBJ_DEFAULT_DEATH             = 0x502C8081
OMM_SOUND_OBJ_BULLY_METAL               = 0x50178081

-- Events
OMM_CAPPY_EVENT_SPAWN                   = 1
OMM_CAPPY_EVENT_HOMING                  = 2
OMM_CAPPY_EVENT_RETURN                  = 3
OMM_CAPPY_EVENT_UNLOAD                  = 4
OMM_CAPPY_EVENT_BOUNCE                  = 5
